---
repository:
  description: An intuitive module for seamless management of UTM parameters
  has_projects: false
  has_wiki: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1

      enforce_admins: true
