name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # Only list the state of node modules if cache wasn't hit
      - if: steps.cache-npm.outputs.cache-hit != 'true'
        name: List the state of node modules
        continue-on-error: true
        run: yarn list

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint --max-warnings 0

      - name: Build Playground
        run: yarn dev:build

      - name: Execute tests
        run: yarn test

      - name: Install playground dependencies
        working-directory: playground
        run: yarn install --frozen-lockfile

      - name: Build playground from its lockfile
        working-directory: playground
        run: yarn build
